### PR TITLE
0.10.0 h7e5bf1

### PR DESCRIPTION
**Pull request by tdejager**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering) *yes*, took the automatic PR as a base

This PR attempts to use the latest version of zig, and also tries to build for osx. But there are still some issues with that, opening it here so it will also run in CI.

### CODE REVIEW

**Comment by xmnlab** [comment]
It looks like he have a memory issue on the liking phase

https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=612288&view=logs&j=656edd35-690f-5c53-9ba3-09c10d0bea97&t=e5c8ab1d-8ff9-5cae-b332-e15ae582ed2d

> A 137 code is issued when a process is terminated externally because of its memory consumption. The operating system's out of memory manager (OOM) intervenes to stop the program before it destabilizes the host. As this example returned 137, you know that demo-binary was stopped because it used too much memory.

Not sure yet how to proceed here, maybe there is a way to have the linking phase consuming less memory or maybe we could increase the memory on CI ...

**Comment by tdejager** [comment]
Hmm, that is an issue, not sure if we could use a different linker under linux e.g.

**Comment by tdejager** [comment]
@conda-forge-admin please rerender

**Comment by tdejager** [comment]
> It looks like it has a memory issue on the liking phase
> 
> https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=612288&view=logs&j=656edd35-690f-5c53-9ba3-09c10d0bea97&t=e5c8ab1d-8ff9-5cae-b332-e15ae582ed2d
> 
> > A 137 code is issued when a process is terminated externally because of its memory consumption. The operating system's out of memory manager (OOM) intervenes to stop the program before it destabilizes the host. As this example returned 137, you know that demo-binary was stopped because it used too much memory.
> 
> Not sure yet how to proceed here, maybe there is a way to have the linking phase consuming less memory or maybe we could increase the memory on CI ...

Also, how did you discern that it hat the exit-code or `137`? Scrolling through the logs I only see an exit code of `2`. I'm probably missing something?

**Comment by tdejager** [comment]
I suppose option B could be a solution as listed here: https://github.com/ziglang/zig/wiki/Building-Zig-From-Source

**Comment by xmnlab** [comment]
Before the error 2 has an error 137

**Comment by xmnlab** [comment]
Not sure if it would fix the problem, but it uses mamba instead of conda for building the package.@ocefpaf told me that mamba is faster but consumes more memory so maybe you could try to replace here mamba by conda https://github.com/conda-forge/zig-feedstock/blob/62269ba51e7d4af468e3848fcee80b95dc127b06/.scripts/build_steps.sh#L60

So there, change "conda mambabuild" to "conda build"

**Comment by wolfv** [comment]
I think our experience was that mamba uses less memory :) (at least that is what the readthedocs people found!).

**Comment by ocefpaf** [comment]
> I think our experience was that mamba uses less memory :) (at least that is what the readthedocs people found!).

Maybe my info is outdated then. To be fair, I only use micromamba lately :-)

**Comment by xmnlab** [comment]
> I suppose option B could be a solution as listed here: https://github.com/ziglang/zig/wiki/Building-Zig-From-Source#option-b-use-a-pre-built-zig-binary

no objection from my side, maybe we could try it and check with the conda-forge core if it is a valid approach here.

**Comment by xmnlab** [comment]
it seems this PR fixed the problem: https://github.com/ziglang/zig/pull/13560

@ocefpaf what would be a better approach to have it here?
get the source directly from that commit? or maybe create a patch file with all changes since the tag was released?

**Comment by ocefpaf** [comment]
> @ocefpaf what would be a better approach to have it here?
> get the source directly from that commit? or maybe create a patch file with all changes since the tag was released?

Usually we patch small things but those changes are 68 commits and 579 file changes!!! What are the chances of getting a new release? If not, one alternative is to get the source from that commit but publish it as a dev release following CFEP-05.

**Comment by xmnlab** [comment]
got it .. thanks for the explanation @ocefpaf ! appreciate that

**Comment by tdejager** [comment]
Probably this will be included in the next zig release I suppose, but then you would be missing 0.10 from conda-forge

**Comment by xmnlab** [comment]
> What are the chances of getting a new release?

@ocefpaf , the estimate data for that is by the end of may: https://github.com/ziglang/zig/milestone/17 

> one alternative is to get the source from that commit but publish it as a dev release following CFEP-05.

@tdejager is it something that you would like to work on?

**Comment by tdejager** [comment]
@wolfv is trying with more memory (swap) in the Azure vm. Which would still be the easiest I think

**Comment by tdejager** [comment]
Seems like 2 things going on:

1. Missing `pthread_nonshared` for the linux64 build. Not sure what we would need to depend on to get this resolved.
2. In the OSX build unpacking the system sdk runs into a problem. Maybe because it's being untarred while also being xz compressed. See: https://askubuntu.com/a/407911 . Don't know if that is still relevant.

**Comment by wolfv** [comment]
Worst case adding a symlink might work (is statically linked anyways), haha (`ln -s /usr/lib/libpthread_nonshared.a $BUILD_PREFIX/...`)

**Comment by xmnlab** [comment]
> Worst case adding a symlink might work (is statically linked anyways), haha (`ln -s /usr/lib/libpthread_nonshared.a $BUILD_PREFIX/...`)

@tdejager , is it something you could do? Thanks

**Comment by pavelzw** [comment]
Nowadays you can also create a swapfile, but I think only for linux runners. https://github.com/conda-forge/polars-feedstock/blob/81713313ff444aea8c755d9e4fcb7102555dde3a/conda-forge.yml#L13-L15

https://github.com/conda-forge/conda-smithy/pull/1751

**Comment by jakirkham** [comment]
Do we need 0.10.0 specifically or would 0.11.0 be ok? Asking since that release came out a couple months ago so is a bit more recent (and may have addressed some of these build issues)

**Comment by pavelzw** [comment]
I tried v0.11.0 in #9. One major problem is that zig requires glibc >=2.25. Not sure how this is handled in conda-forge packages.

**Comment by jakirkham** [comment]
Oh interesting. Maybe we should try 0.10.1 first then

**Comment by MementoRC** [comment]
@wolfv Do you think we still need 0.10.0? I think I have an acceptable 0.13.0 build recipe for linux x86_64/aarch64 and osx. If so, I would prefer to build it with the newer recipe in a separate branch

**Comment by jakirkham** [comment]
It looks like we are already on 0.12.0: https://github.com/conda-forge/zig-feedstock/pull/10

Maybe we should close?

Thanks all for the efforts on getting this updated! 🙏

**Comment by MementoRC** [comment]
@jakirkham Yes, I'd prefer close and reopen as a separate branch if needed. We are actually on `0.13.0`, adding osx and aarch64 ;P

We are having a lot of difficulties with `win` and `ppc64le`. I would like to try a `2xlarge` for windows (I saw a PR related to that, but don't know if I can simply apply it to test out the win build)

**Comment by jakirkham** [comment]
Please go ahead with a new PR. We can discuss CI setup in that PR

**Comment by MementoRC** [comment]
Closing. If needed, we will create a branch from the latest recipe

**Pull request closed without merging**
