### PR TITLE
DBG: Add windows MSVC build from source

### PR DESCRIPTION
**Pull request by MementoRC**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by MementoRC** [comment]
@jakirkham When trying to build from source, the last step just hangs there for 6hrs (timeout). On other tries, I did see a LLVM: Out of memory error, which made me wonder if this is not the issue here

**Comment by jakirkham** [comment]
Could try enabling a pagefile on Windows. Here's [an example from NumPy]( https://github.com/conda-forge/numpy-feedstock/blob/10b2fa510901ba22db1a00b81e5aa4c646a11b03/conda-forge.yml#L1-L4 )

**Comment by jakirkham** [comment]
@conda-forge-admin please rerender

**Comment by MementoRC** [comment]
Thanks, just realized I forgot to

**Comment by MementoRC** [comment]
No luck, I guess

**Pull request closed without merging**
