### PR TITLE
FEAT: 0.13.0. Added aarch64 and osx

### PR DESCRIPTION
**Pull request by MementoRC**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by MementoRC** [comment]
@wolfv @jakirkham This recipe builds zig using the upstream binary distribution to compile itself. Both native builds (at least) can use CMake from source, they take about 2x longer. I kept that option in the recipe (using and environment flag to switch to it)

linux-ppc64le is very difficult to get going, I tried several approaches:
   - Build with CMake native (on Travis)
   - Build with upstream bootstrap native (on Travis)
   - Build cross-compiled CMake x86_64->ppc64le with qemu
   - Build cross-compiled with upstream binary
 They all fail for various reasons, oddly the upstream binary does not seem to even run on Travis.

win build is even worse

So, I'd like to merge this PR if you approve (I'll try not to modify it

**Comment by MementoRC** [comment]
@pavelzw FYI

**Comment by wolfv** [comment]
Hi @MementoRC - excellent stuff! I am wondering what needs to be done for `osx-arm64`? :)

**Comment by wolfv** [comment]
I honestly don't know either. Maybe we can ask @andrewrk .

From a selfish perspective I am more interested in `osx-arm64` then `ppc64le` (which is probably the least used platform on conda-forge) :) 

By the way, we had some users build some examples with zig for `pixi` in the ["prefix" Discord](https://discord.gg/kKV8ZxyzY4): https://github.com/kassane/zig-sdl-pixi-sample

Hopefully we can move that to the conda-forge build of `zig` soon :)

**Comment by MementoRC** [comment]
It'd be great if he can take a look and correct the recipes. I left some issues on the repo, but no hints or feedback came trhough. I do admit that I must be missing some fundamentals about zig, this is by far the hardest recipe I worked on. I mean there are at least 4 ways of building it between bootstrap/cmake and native/cross - though, I suspect the cross zig may not use the existing cross-environment

**Comment by MementoRC** [comment]
> Hopefully we can move that to the conda-forge build of `zig` soon :)

What do you mean? `pixi` is already a conda-forge package

**Comment by wolfv** [comment]
Yes, but the example is using `ziglang` from PyPI (which is a repack of the official binaries into wheels).

**Comment by wolfv** [comment]
https://github.com/kassane/zig-sdl-pixi-sample/blob/d821a61def66fe278225536ed5ff0d05d27cc132/pixi.toml#L17-L18

**Comment by MementoRC** [comment]
He could already use 0.13.0 from conda for the few arch, right? just as a test. Are you part of a zig community? are you in touch with Andrew?

**Comment by wolfv** [comment]
Nope, I am just a conda-forge enthusiast :)

**Comment by andrewrk** [comment]
Hello, I have been pinged.

I have not taken the time to read the patch, but I highly recommend to use the standard cmake build process for building Zig from source. Using a prior zig version to build itself is often useful for developers, but it is a less robust way to obtain a build for users, and will sometimes fail, or sometimes produce incorrect results, when breaking changes are made to the compiler.

On the other hand, the standard cmake build process will always work correctly, every time, for every commit.

**Comment by MementoRC** [comment]
@andrewrk Cool, thank you for the diligent reply. We took the approach of using the binary distribution as our "bootstrap", but we will revisit the CMake build (it's jusr quite slower) based on your input.

We are having extreme difficulties with the windows build (cmake, msvc/clang/gcc or zig) and the ppc64le build and would love to take a look at your build recipe, so far none of the solution works (bootstrap, native, cmake or zig combination). We have PRs that attempt to look at each building procedures

We'll go back to the drawing board and try to ping you astutely when we feel stuck. Thank you

**Comment by andrewrk** [comment]
Feel free to file an issue on the ziglang/zig repository if you encounter problems with the standard build process. That will be a productive place to troubleshoot.

**Comment by MementoRC** [comment]
I posted an issue a few days ago : https://github.com/ziglang/zig/issues/20335 - since you have a binary distribution for PPC64LE, I must be missing something - though the binary distribution does not run on the Travis runner that I have tried

**Comment by xmnlab** [comment]
sorry for the delay @MementoRC 
I was a bit "offline" the past few weeks .. thanks for moving this forward
I am starting now to check all my github notifications XD

**Comment by MementoRC** [comment]
It looks a bit messy right now. we're close on osx-arm64, but struggling with ppc64le and windows

**Pull request merged**
