### PR TITLE
0.12.0 fix failed build

### PR DESCRIPTION
**Pull request by MementoRC**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by MementoRC** [comment]
@xmnlab @pavelzw This proposal uses the latest release of `sbcl` that does not require GLIBC>2.28 as a bootstrap to compile `sbcl` from source. We could probably switch back to using `gcc` instead, but I wanted to post something that you can review

The key was to set a TARGET other than `native`, but patch the source to still trigger the `look for llvm`, then add a few `patchelf` during the multi-stage build of `zig`

**Comment by xmnlab** [comment]
thanks for working on that @MementoRC 
as I am not working on this package recently, I  don't have too much to add to the review.

the only thing I saw, was a missing new line at the end of the file recipe/build.sh, but it is too small "issue", if you have more things to push, it would be nice to fix that. otherwise, it is fine.

**Review by xmnlab — APPROVED** [review]
LGTM!

**Comment by MementoRC** [comment]
Oops, you're right, let's not do my usual `pile-it up till it's a mess`

**Pull request merged**
