### PR TITLE
Try cmake build and osx-arm64 

### PR DESCRIPTION
**Pull request by wolfv**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by MementoRC** [comment]
This approach would need a cross-emulator, would it not? Zig via CMake uses a 3 stage process, first build zig1, which is used to create the zig2.c file

**Comment by wolfv** [comment]
No idea! But it worked locally on osx-arm64 ... there was also some variable for finding LLVM without a running llvm-config. I just wanted to try :)

**Comment by MementoRC** [comment]
Oh right, but conda does not have an `arm64` runner, we can only cross-compile for now, but there no emulator, afaik

**Comment by wolfv** [comment]
Yep. I think what we should probably do is install `zig` using `mamba` inside the build process, and then use that to (cross-)compile the `osx-arm64` zig and skip the whole CMake stuff here. I'll not be able to hack on that tonight though :) Maybe I'll give it a shot tomorrow but I also saw that you might already have solved it in the other PR?!

I did something similar recently for `ruby`: https://github.com/conda-forge/ruby-feedstock/blob/05d7453a068f542a4e198ff1c933ff4e23230851/recipe/build.sh#L8-L9
But maybe I also copied that from your SBCL work :)

**Comment by MementoRC** [comment]
Sure, that's what I am doing here: https://github.com/conda-forge/zig-feedstock/pull/35 - But because zig does not always build itself (0.12.0 cannot build 0.13.0), I use the binary that they distribute

**Comment by MementoRC** [comment]
That recipe becomes way too complex, I am getting lost. I am thinking to separate the builds for each specific platform rather than trying to make it fit together in one script

**Comment by MementoRC** [comment]
@wolfv This can be closed, correct?

**Comment by MementoRC** [comment]
> @wolfv This can be closed, correct?

OMG, yes, I have been away for too long. Thx. Closing

**Pull request closed without merging**
