### PR TITLE
FEAT: Use conda zig rather than upstream binary dist

### PR DESCRIPTION
**Pull request by MementoRC**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by MementoRC** [comment]
@conda-forge-admin rerender

**Comment by MementoRC** [comment]
@xmnlab I removed the dependencies on the upstream binaries. In the pipeline, I plan to transition to revisit the windows build, I seem to make progress with the latest gcc 13. Also, it'll be good to use cmake, but @xhochy has not yet greenlighted the use of a local qemu with execve() intercept.

**Comment by xhochy** [comment]
> @xmnlab I removed the dependencies on the upstream binaries. In the pipeline, I plan to transition to revisit the windows build, I seem to make progress with the latest gcc 13. Also, it'll be good to use cmake, but @xhochy has not yet greenlighted the use of a local qemu with execve() intercept.

It's not the best, but for now I don't see a good alternative and don't have time to investigate myself: so go ahead!

**Comment by MementoRC** [comment]
> 
> It's not the best, but for now I don't see a good alternative and don't have time to investigate myself: so go ahead!

Would it be slightly better to make a separate `qemu-execve` recipe that other maintainer facing the same issue could use. Ideally, it would be used sparingly, only when the qemu-static already available is not working.

**Pull request merged**
